#ifndef ENUMES_H
#define ENUMES_H

enum MSGOREVENT { RES_MSG, RES_EVENT, RES_OTHER };
enum UTYPE { UT_PM, UT_PZ, UT_ENC, UT_SENS, UT_NONE }; 
enum SCANSTAGE { INITIAL, MEASURE, ONESTEP, SCANEND };
enum LINLOG { LIN, LOG, NOLINLOG };
enum RELABS { REL, ABS };
enum SPEED { SPEED_HIGH, SPEED_MIDDLE, SPEED_LOW, SPEED_ERR };
enum POSNEG { POSITIVE, NEGATIVE };
enum MOTORTYPE { MTYPE_PM, MTYPE_PZ, MTYPE_NONE };
enum SHOWUNIT { PULSE, METRICUNIT, NOUNIT };
enum STYPE{ KEITHLEY6485, IONCH, DUMMYPEAK };

#endif
