######################################################################
# Automatically generated by qmake (2.01a) Sun Feb 17 16:08:52 2013
######################################################################

TEMPLATE = subdirs

# Directories
SUBDIRS += doc.pro
