######################################################################
# Automatically generated by qmake (2.01a) Fri Feb 1 16:11:29 2013
######################################################################

TEMPLATE = subdirs

# Directories
SUBDIRS += doc.pro
